name: ThumbBar

current: 0.1.0

web: "[github.com/eerne/ThumbBar](http://github.com/eerne/ThumbBar)"

description: "Show, hide and scroll thumbnails with rpflorence/SlideShow"

authors: "[Enrique Erne](http://mild.ch/)"

license: "MIT License"

copyright: "&copy; 2010, Enrique Erne"

sources:
  - "Source/ThumbBar"
  
# Values for MooTools forge
  
author: tofu

demo: http://2011.mild.ch/projects/thumbbar.html

category: interface

tags: [menu, gallery, slideshow, thumbs, slide, scroll]
